"""Append Financial OS training data to SpiderNetOS Atlas training files."""
import json
import os

BASE = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "training_data")

# ─── SFT entries ──────────────────────────────────────────────────────────
sft_entries = [
    {
        "messages": [
            {"role": "user", "content": "Build a complete Financial OS for SpiderNetOS — double-entry bookkeeping, invoicing, payments, portfolios, reporting, fraud detection, everything."},
            {"role": "assistant", "content": "I'll build the complete Financial OS following SpiderNetOS architecture conventions. This is a full-stack implementation that you can replicate for any vertical.\n\n**The SpiderNetOS Implementation Pattern (replicable for ANY app):**\n\n1. **Migrations** → Define the data model in `backend/database/migrations/` with UUID PKs, tenant_id, proper indexes\n2. **Models** → Eloquent models in `backend/app/Models/` with HasUuids, fillable, casts, relationships, scopes\n3. **Services** → Business logic in `backend/app/Services/{Domain}/` with EventStore integration for audit\n4. **Controllers** → HTTP handlers in `backend/app/Http/Controllers/{Domain}/` with validation\n5. **Routes** → API endpoints in `backend/routes/api.php` under protected middleware\n6. **Integration Adapters** → External services in `backend/app/Services/Integrations/`\n7. **Feature Pack** → YAML pack in `packages/feature-packs/{domain}/pack.yaml`\n8. **MCP Tools** → AI-accessible tools in `services/mcp-server/src/server.ts`\n9. **AI Agents** → Python agents in `intelligence/agents/{domain}_agent.py`\n10. **Cockpit UI** → Vue components in `cockpit/src/views/{domain}/` + router updates\n\nFor the Financial OS, this means 15 migrations, 17 models, 6 services, 5 controllers, 30+ routes, Stripe adapter, feature pack, 5 MCP tools, 2 Python agents, and 5 Vue views."}
        ],
        "metadata": {"quality_score": 4, "source": "cursor", "tags": ["financial-os", "architecture", "replicable-pattern", "full-stack"]}
    },
    {
        "messages": [
            {"role": "user", "content": "What is the general SpiderNetOS pattern for building any new feature or vertical application?"},
            {"role": "assistant", "content": "The SpiderNetOS pattern is a 10-step pipeline that works for ANY feature:\n\n**Step 1: Migrations** (`backend/database/migrations/`)\n- UUID primary keys, tenant_id on every table\n- DECIMAL(19,4) for money, proper indexes\n- Composite unique constraints where needed\n- `down()` method with Schema::dropIfExists()\n\n**Step 2: Models** (`backend/app/Models/`)\n- `use HasUuids` trait\n- fillable arrays for all columns\n- casts for dates, decimals, arrays\n- BelongsTo/HasMany relationships\n- Query scopes: `scopeForTenant`, `scopeActive`, `scopeOfType`\n\n**Step 3: Services** (`backend/app/Services/{Domain}/`)\n- Inject EventStore for audit trail\n- All writes go through EventStore::append()\n- Business logic, calculations, state transitions\n- DB::transaction for atomicity\n\n**Step 4: Controllers** (`backend/app/Http/Controllers/{Domain}/`)\n- Request validation with Laravel rules\n- Delegate to services (thin controllers)\n- Return JSON with consistent `{data: ...}` format\n- Pagination for list endpoints\n\n**Step 5: Routes** (`backend/routes/api.php`)\n- Group under prefix with auth:sanctum + tenant middleware\n- RESTful naming conventions\n- Separate admin/platform routes with role guards\n\n**Step 6: Integration Adapters** (`backend/app/Services/Integrations/`)\n- Constructor takes tenantId + credentials\n- Methods return arrays\n- Use Laravel Http facade for API calls\n- Follow existing adapter patterns (StripeAdapter, CrmAdapter)\n\n**Step 7: Feature Pack** (`packages/feature-packs/{domain}/pack.yaml`)\n- metadata: id, version, display_name\n- spec: dynamic_agents, ste_chains, policies\n- database: list of migration filenames\n- integrations: provider configurations\n\n**Step 8: MCP Tools** (`services/mcp-server/src/server.ts`)\n- Define Tool objects with name, description, inputSchema\n- Add to ListToolsRequestSchema handler\n- Implement in CallToolRequestSchema switch\n\n**Step 9: AI Agents** (`intelligence/agents/{domain}_agent.py`)\n- Extend AgentBase with capabilities list\n- Implement execute() with AST type routing\n- Use meta_planner, cost_governor, memory_graph, db_pool\n- _query_db() helper with error handling\n\n**Step 10: Cockpit UI** (`cockpit/src/views/{domain}/`)\n- Vue 3 components with setup syntax\n- Use existing CSS classes (dct-card, dct-btn-primary, dct-pill-*)\n- Lazy-load in router: `const View = () => import(...)`\n- Add routes with requiresAuth: true\n\nThis pattern is replicable for any domain: HR, logistics, healthcare, e-commerce, etc."}
        ],
        "metadata": {"quality_score": 4, "source": "cursor", "tags": ["spidernetos-pattern", "replicable", "architecture", "methodology"]}
    },
    {
        "messages": [
            {"role": "user", "content": "Create the database migrations for the Financial OS. Show me the key design decisions."},
            {"role": "assistant", "content": "Created 15 migrations. Key design decisions:\n\n**Financial precision:** All money fields use `DECIMAL(19,4)` — never FLOAT. This prevents rounding errors in financial calculations.\n\n**Multi-tenant isolation:** Every table has `tenant_id` as a foreign key index. All queries are scoped by tenant.\n\n**UUID primary keys:** Consistent with SpiderNetOS convention. Use `$table->uuid('id')->primary()`.\n\n**Unique constraints:** Business identifiers are unique per tenant — `invoice_number`, `transaction_number`, `payment_number` all use format `PREFIX-YYYYMMDD-NNNNNN`.\n\n**Idempotency:** `transactions` table has `idempotency_key` unique column to prevent double-processing.\n\n**Audit trail:** `ledger_entries` has `event_log_id` linking back to the EventStore event.\n\n**Indexes:** Composite indexes for common queries — `(tenant_id, status)`, `(tenant_id, posted_at)`, `(tenant_id, due_date)`.\n\n**Soft state:** Status columns use constrained strings with defaults — `status('draft')`, `status('active')`.\n\n**Nullable relationships:** `payments.invoice_id` is nullable since payments can exist without invoices.\n\n**Crypto precision:** `portfolio_positions.quantity` uses `DECIMAL(19,8)` to support fractional crypto holdings."}
        ],
        "metadata": {"quality_score": 4, "source": "cursor", "tags": ["financial-os", "migrations", "database-design", "best-practices"]}
    },
    {
        "messages": [
            {"role": "user", "content": "Show me how to create Eloquent models following SpiderNetOS conventions for the Financial OS."},
            {"role": "assistant", "content": "Every Financial OS model follows this exact pattern:\n\n```php\n<?php\nnamespace App\\Models;\n\nuse Illuminate\\Database\\Eloquent\\Model;\nuse Illuminate\\Database\\Eloquent\\Relations\\BelongsTo;\nuse Illuminate\\Database\\Eloquent\\Relations\\HasMany;\n\nclass FinancialAccount extends Model\n{\n    use \\Illuminate\\Database\\Eloquent\\Concerns\\HasUuids;\n\n    protected $fillable = [\n        'tenant_id', 'name', 'type', 'currency', 'status', 'balance', ...\n    ];\n\n    protected $casts = [\n        'balance' => 'decimal:4',\n        'metadata' => 'array',\n        'opened_at' => 'datetime',\n    ];\n\n    public function tenant(): BelongsTo {\n        return $this->belongsTo(Tenant::class);\n    }\n\n    public function ledgerEntries(): HasMany {\n        return $this->hasMany(LedgerEntry::class, 'account_id');\n    }\n\n    public function scopeForTenant($query, string $tenantId) {\n        return $query->where('tenant_id', $tenantId);\n    }\n\n    public function scopeActive($query) {\n        return $query->where('status', 'active');\n    }\n}\n```\n\n**Rules:**\n- Always use `HasUuids` trait\n- `$fillable` includes ALL columns except id/timestamps\n- `$casts` for decimals ('decimal:4'), arrays ('array'), datetimes ('datetime'), booleans ('boolean')\n- `BelongsTo` for parent relations, `HasMany` for children\n- `scopeForTenant($query, string $tenantId)` on every model\n- Domain-specific scopes like `scopeActive`, `scopeOfType`\n- Model methods for business logic (e.g., `PortfolioPosition::updatePrice()`)"}
        ],
        "metadata": {"quality_score": 4, "source": "cursor", "tags": ["financial-os", "models", "eloquent", "conventions"]}
    },
    {
        "messages": [
            {"role": "user", "content": "Implement the LedgerService with double-entry bookkeeping. How does it work?"},
            {"role": "assistant", "content": "The `LedgerService` in `backend/app/Services/Financial/LedgerService.php` implements double-entry bookkeeping:\n\n```php\npublic function createJournalEntry(string $tenantId, string $sourceId, string $destId, string $amount, string $currency = 'USD', string $desc = ''): Transaction\n{\n    return DB::transaction(function () use (...) {\n        // 1. Create the transaction record\n        $tx = Transaction::create([\n            'tenant_id' => $tenantId,\n            'transaction_number' => $this->generateTransactionNumber($tenantId),\n            'type' => 'journal_entry', 'amount' => $amount, 'status' => 'completed', ...\n        ]);\n\n        // 2. Create paired ledger entries (credit + debit must balance)\n        $this->createDoubleEntry($tenantId, $tx->transaction_number, $sourceId, $destId, $amount, $currency, $desc);\n\n        // 3. Append to event_log for immutable audit trail\n        $this->eventStore->append($tenantId, 'ledger', $tx->id, 'ledger.entry_posted', [...]);\n\n        // 4. Update account balances atomically\n        $this->updateAccountBalances($tenantId, $sourceId, $destId, $amount);\n\n        return $tx;\n    });\n}\n\nprivate function createDoubleEntry(string $tenantId, string $txnNum, string $sourceId, string $destId, string $amount, string $currency, string $desc): void\n{\n    // Credit: money leaves source account\n    LedgerEntry::create(['tenant_id' => $tenantId, 'account_id' => $sourceId, 'transaction_id' => $txnNum, 'side' => 'credit', 'amount' => $amount, ...]);\n    // Debit: money enters destination account\n    LedgerEntry::create(['tenant_id' => $tenantId, 'account_id' => $destId, 'transaction_id' => $txnNum, 'side' => 'debit', 'amount' => $amount, ...]);\n}\n```\n\n**The invariant:** total debits must always equal total credits. `createDoubleEntry()` guarantees this by creating exactly 2 entries with the same amount.\n\n**Other methods:**\n- `getTrialBalance()` — groups by account, sums debits/credits, calculates net\n- `getGeneralLedger($accountId)` — all entries for one account in date range\n- `getCashFlow()` — categorizes entries into operating/investing/financing"}
        ],
        "metadata": {"quality_score": 4, "source": "cursor", "tags": ["financial-os", "ledger", "double-entry", "event-sourcing", "service"]}
    },
    {
        "messages": [
            {"role": "user", "content": "Implement the InvoiceService and PaymentService for the Financial OS."},
            {"role": "assistant", "content": "**InvoiceService** (`backend/app/Services/Financial/InvoiceService.php`):\n\n```php\npublic function createInvoice(string $tenantId, array $data, array $lineItems = []): Invoice\n{\n    return DB::transaction(function () use ($tenantId, $data, $lineItems) {\n        // Calculate from line items — never trust client-side totals\n        $subtotal = 0;\n        foreach ($lineItems as $item) $subtotal += ($item['quantity'] ?? 1) * $item['unit_price'];\n        $tax = ($data['tax_rate'] ?? 0) * $subtotal / 100;\n        $total = $subtotal + $tax - ($data['discount_amount'] ?? 0);\n\n        $invoice = Invoice::create([\n            'invoice_number' => 'INV-' . date('Ymd') . '-' . str_pad((string)(Invoice::where('tenant_id', $tenantId)->count() + 1), 6, '0', STR_PAD_LEFT),\n            'subtotal' => $subtotal, 'tax_amount' => $tax, 'total_amount' => $total, ...\n        ]);\n\n        foreach ($lineItems as $item) {\n            InvoiceLineItem::create(['invoice_id' => $invoice->id, 'total' => ($item['quantity'] ?? 1) * $item['unit_price'], ...]);\n        }\n\n        $this->eventStore->append($tenantId, 'invoice', $invoice->id, 'invoice.created', ['total_amount' => $total]);\n        return $invoice->load('lineItems');\n    });\n}\n```\n\nLifecycle: `sendInvoice()` draft→sent, `markInvoicePaid()` →paid, `cancelInvoice()` (throws if already paid).\n\n**PaymentService** (`backend/app/Services/Financial/PaymentService.php`):\n\n```php\npublic function recordPayment(string $tenantId, string $amount, string $method, ?string $idempotencyKey = null): Payment\n{\n    return DB::transaction(function () use (...) {\n        if ($idempotencyKey) {\n            $existing = Payment::where('idempotency_key', $idempotencyKey)->first();\n            if ($existing) return $existing; // Idempotent — safe to retry\n        }\n        $payment = Payment::create([...]);\n        $this->eventStore->append($tenantId, 'payment', $payment->id, 'payment.received', ['amount' => $amount]);\n        return $payment;\n    });\n}\n```\n\nOutgoing payments: `initiatePayment()` → pending Transaction, `completePayment()` or `failPayment()` to transition."}
        ],
        "metadata": {"quality_score": 4, "source": "cursor", "tags": ["financial-os", "invoices", "payments", "idempotency", "services"]}
    },
    {
        "messages": [
            {"role": "user", "content": "Implement the FinancialGovernor for fraud detection and budget enforcement."},
            {"role": "assistant", "content": "`FinancialGovernor` in `backend/app/Services/Financial/FinancialGovernor.php`:\n\n**Budget enforcement:**\n```php\npublic function checkBudgetLimit(string $tenantId, string $budgetId, float $amount): array\n{\n    $budget = Budget::findOrFail($budgetId);\n    $utilization = (($budget->spent + $amount) / $budget->amount) * 100;\n    if ($utilization >= 100) {\n        $this->createAlert($tenantId, 'budget_exceeded', 'critical', ...);\n        return ['allowed' => false, 'reason' => 'Budget exceeded'];\n    }\n    if ($utilization >= $budget->alert_threshold) {\n        $this->createAlert($tenantId, 'budget_warning', 'warning', ...);\n    }\n    return ['allowed' => true, 'utilization' => $utilization];\n}\n```\n\n**Fraud risk scoring:**\n```php\npublic function detectFraudulentTransaction(string $tenantId, string $txnId, float $amount, string $method, ?string $email = null): array\n{\n    $risk = 0; $flags = [];\n    if ($amount > 10000) { $risk += 20; $flags[] = 'large_amount'; }\n    if ($email && Transaction::where('counterparty_email', $email)->count() === 0 && $amount > 1000) { $risk += 30; $flags[] = 'new_counterparty'; }\n    if (Transaction::where('created_at', '>=', now()->subMinutes(30))->count() > 5) { $risk += 25; $flags[] = 'high_frequency'; }\n    if ((int)now()->format('H') >= 2 && (int)now()->format('H') <= 5) { $risk += 15; $flags[] = 'unusual_hour'; }\n    if ($risk >= 50) { $this->createAlert($tenantId, 'fraud_suspected', 'critical', ...); }\n    return ['risk_score' => $risk, 'status' => $risk >= 50 ? 'flagged' : 'approved', 'flags' => $flags];\n}\n```\n\nFlags trigger FinancialAlert entries visible in the dashboard. Score >= 50 requires human approval."}
        ],
        "metadata": {"quality_score": 4, "source": "cursor", "tags": ["financial-os", "fraud-detection", "budget", "governance", "risk-scoring"]}
    },
    {
        "messages": [
            {"role": "user", "content": "Implement the PortfolioService and ReportingService for the Financial OS."},
            {"role": "assistant", "content": "**PortfolioService** (`backend/app/Services/Financial/PortfolioService.php`):\n\n```php\npublic function addPosition(string $portfolioId, string $tenantId, string $assetType, string $symbol, string $qty, string $price): PortfolioPosition\n{\n    $existing = PortfolioPosition::where('portfolio_id', $portfolioId)->where('symbol', $symbol)->first();\n    if ($existing) {\n        // Average cost: (old_cost * old_qty + new_price * new_qty) / total_qty\n        $totalQty = $existing->quantity + $qty;\n        $existing->quantity = $totalQty;\n        $existing->avg_cost = (($existing->avg_cost * $existing->quantity) + ($price * $qty)) / $totalQty;\n        $existing->save();\n        return $existing;\n    }\n    return PortfolioPosition::create([...]);\n}\n\npublic function executeTrade(string $portfolioId, string $tenantId, string $assetType, string $symbol, string $side, string $qty, string $price): Trade\n{\n    return DB::transaction(function () use (...) {\n        $trade = Trade::create([...]);\n        if ($side === 'buy') $this->addPosition(...);\n        else { $pos = PortfolioPosition::where(...)->first(); $pos->quantity -= $qty; $pos->quantity <= 0 ? $pos->delete() : $pos->save(); }\n        $this->eventStore->append($tenantId, 'trade', $trade->id, 'trade.executed', [...]);\n        return $trade;\n    });\n}\n```\n\n**ReportingService** (`backend/app/Services/Financial/ReportingService.php`):\n- `generateProfitAndLoss()` — paid invoices revenue, sent payments expenses, net = revenue - expenses\n- `generateBalanceSheet()` — assets (wallets + receivables), liabilities (payables), equity = assets - liabilities\n- `generateCashFlowStatement()` — inflows (received) vs outflows (sent)\n- `getAgingReport()` — unpaid invoices bucketed: current, 1-30d, 31-60d, 61-90d, 90+d\n- `getDashboardMetrics()` — revenue this month vs last with growth %, outstanding invoices, pending payments, wallet balance"}
        ],
        "metadata": {"quality_score": 4, "source": "cursor", "tags": ["financial-os", "portfolio", "reporting", "services"]}
    },
    {
        "messages": [
            {"role": "user", "content": "Create the financial API controllers and routes. Show me the pattern."},
            {"role": "assistant", "content": "5 controllers in `backend/app/Http/Controllers/Financial/`. Pattern:\n\n```php\n<?php\nnamespace App\\Http\\Controllers\\Financial;\n\nuse App\\Http\\Controllers\\Controller;\nuse App\\Services\\Financial\\LedgerService;\nuse Illuminate\\Http\\JsonResponse;\nuse Illuminate\\Http\\Request;\n\nclass LedgerController extends Controller\n{\n    public function __construct(private readonly LedgerService $ledgerService) {}\n\n    public function index(Request $request): JsonResponse\n    {\n        $tenant = $request->attributes->get('tenant');\n        $entries = LedgerEntry::forTenant($tenant->id)->with('account')->orderByDesc('posted_at')->paginate($request->get('per_page', 20));\n        return response()->json(['data' => $entries]);\n    }\n\n    public function journalEntry(Request $request): JsonResponse\n    {\n        $tenant = $request->attributes->get('tenant');\n        $validated = $request->validate([\n            'source_account_id' => 'required|uuid|exists:financial_accounts,id',\n            'destination_account_id' => 'required|uuid|exists:financial_accounts,id',\n            'amount' => 'required|numeric|min:0.01',\n        ]);\n        $tx = $this->ledgerService->createJournalEntry($tenant->id, $validated['source_account_id'], $validated['destination_account_id'], $validated['amount']);\n        return response()->json(['data' => $tx], 201);\n    }\n}\n```\n\n**Rules:** Constructor injection of services, `$request->attributes->get('tenant')` for tenant scope, validate before calling service, return `['data' => ...]` format, paginate lists, 201 for creates.\n\n**Routes in `api.php`:**\n```php\nRoute::middleware(['auth:sanctum', 'tenant', 'onboarding.required', 'cost.limit', 'throttle:api'])\n    ->prefix('financial')\n    ->group(function () {\n        Route::get('/ledger', [LedgerController::class, 'index']);\n        Route::post('/ledger/journal-entry', [LedgerController::class, 'journalEntry']);\n        // ... 30+ more endpoints\n    });\n```"}
        ],
        "metadata": {"quality_score": 4, "source": "cursor", "tags": ["financial-os", "controllers", "api", "routes", "pattern"]}
    },
    {
        "messages": [
            {"role": "user", "content": "Create the Stripe adapter for the Financial OS."},
            {"role": "assistant", "content": "`StripeAdapter` in `backend/app/Services/Integrations/StripeAdapter.php`:\n\n```php\n<?php\ndeclare(strict_types=1);\nnamespace App\\Services\\Integrations;\n\nuse Illuminate\\Support\\Facades\\Http;\n\nclass StripeAdapter\n{\n    private string $apiKey;\n    private string $webhookSecret;\n\n    public function __construct(protected readonly string $tenantId, protected readonly array $credentials)\n    {\n        $this->apiKey = $credentials['api_key'] ?? throw new \\RuntimeException('Stripe API key required');\n        $this->webhookSecret = $credentials['webhook_secret'] ?? '';\n    }\n\n    public function createPaymentIntent(float $amount, string $currency, ?string $customerId = null, array $metadata = []): array\n    {\n        $response = Http::withToken($this->apiKey)->asForm()->post('https://api.stripe.com/v1/payment_intentions', [\n            'amount' => (int)($amount * 100), // Stripe uses cents\n            'currency' => $currency,\n            'customer' => $customerId,\n            'metadata' => json_encode($metadata),\n        ]);\n        if ($response->failed()) throw new \\RuntimeException(\"Stripe API error: \" . $response->body());\n        return $response->json();\n    }\n\n    public function handleWebhook(string $payload, string $signature): array\n    {\n        $event = \\Stripe\\Webhook::constructEvent($payload, $signature, $this->webhookSecret);\n        return match ($event->type) {\n            'payment_intent.succeeded' => ['type' => 'payment_succeeded', 'amount' => $event->data->object->amount_received / 100],\n            'invoice.paid' => ['type' => 'invoice_paid', 'amount' => $event->data->object->amount_paid / 100],\n            'customer.subscription.deleted' => ['type' => 'subscription_cancelled'],\n            default => ['type' => $event->type, 'data' => $event->data->object],\n        };\n    }\n}\n```\n\n**Key:** Amounts * 100 for Stripe's cent-based API. Webhook uses Stripe's signature verification. Constructor throws if api_key missing. Follows the adapter pattern used by CrmAdapter."}
        ],
        "metadata": {"quality_score": 4, "source": "cursor", "tags": ["financial-os", "stripe", "adapter", "payments", "webhooks"]}
    },
    {
        "messages": [
            {"role": "user", "content": "Create the financial feature pack YAML and explain what it defines."},
            {"role": "assistant", "content": "`packages/feature-packs/financial-services/pack.yaml`:\n\n```yaml\nmetadata:\n  id: financial-services\n  version: 1.0.0\n  display_name: \"Financial OS\"\n  description: \"Comprehensive financial operating system\"\nspec:\n  provides:\n    dynamic_agents:\n      - id: finance-agent\n        capabilities: [ledger-query, report-generation, cash-flow-analysis, budget-optimization, invoice-chasing, forecasting]\n      - id: compliance-agent\n        capabilities: [transaction-monitoring, fraud-detection, kyc-screening, audit-trail, alert-management]\n      - id: portfolio-agent\n        capabilities: [portfolio-analysis, risk-assessment, trade-execution, performance-tracking, rebalancing]\n    ste_chains:\n      - id: payment_lifecycle\n        states: [initiated, processing, completed, failed, refunded]\n      - id: invoice_lifecycle\n        states: [draft, sent, paid, cancelled, overdue]\n    policies:\n      - id: financial-transaction-approval\n        conditions: { transaction_amount: \"> 10000\" }\n        action: \"require_approval\"\n      - id: budget-enforcement\n        conditions: { budget_utilization: \">= 100\" }\n        action: \"block_with_alert\"\n  database:\n    migrations: [15 migration filenames]\n  integrations:\n    stripe: { enabled: true, adapter: App\\Services\\Integrations\\StripeAdapter }\n```\n\n**What it defines:**\n1. **Dynamic agents** — AI agents auto-provisioned when pack is installed\n2. **STE chains** — state machines for payment and invoice lifecycles\n3. **Policies** — governance rules (approval for large transactions, block when budget exceeded)\n4. **Migrations** — list of migration files the pack depends on\n5. **Integrations** — external service adapters with their PHP class paths\n\n**This pattern is replicable for any vertical:** HR pack, logistics pack, healthcare pack, etc."}
        ],
        "metadata": {"quality_score": 4, "source": "cursor", "tags": ["financial-os", "feature-pack", "yaml", "agents", "replicable"]}
    },
    {
        "messages": [
            {"role": "user", "content": "Add financial tools to the MCP server. Show me the pattern."},
            {"role": "assistant", "content": "Updated `services/mcp-server/src/server.ts`. Pattern for adding financial tools:\n\n**1. Define the tool:**\n```typescript\nconst FINANCIAL_LEDGER_TOOL: Tool = {\n    name: \"financial_ledger\",\n    description: \"Query the double-entry ledger\",\n    inputSchema: {\n        type: \"object\",\n        properties: {\n            queryType: { type: \"string\", enum: [\"entries\", \"trial_balance\", \"cash_flow\", \"accounts\"], default: \"entries\" },\n            startDate: { type: \"string\", description: \"YYYY-MM-DD\" },\n            endDate: { type: \"string\", description: \"YYYY-MM-DD\" },\n        },\n        required: [\"queryType\"],\n    },\n};\n```\n\n**2. Register in ListToolsRequestSchema:**\n```typescript\nserver.setRequestHandler(ListToolsRequestSchema, async () => ({\n    tools: [\n        CODE_SEARCH_TOOL, READ_FILE_TOOL, ...existing tools...\n        FINANCIAL_LEDGER_TOOL, FINANCIAL_INVOICES_TOOL, FINANCIAL_REPORT_TOOL, FINANCIAL_DASHBOARD_TOOL, FINANCIAL_PORTFOLIO_TOOL,\n    ],\n}));\n```\n\n**3. Implement in CallToolRequestSchema:**\n```typescript\ncase \"financial_ledger\": {\n    const { queryType = \"entries\", startDate, endDate } = args as { queryType: string; startDate?: string; endDate?: string };\n    const endpoints: Record<string, string> = {\n        entries: \"GET /api/financial/ledger\",\n        trial_balance: \"GET /api/financial/ledger/trial-balance\",\n        cash_flow: \"GET /api/financial/ledger/cash-flow\",\n    };\n    return { content: [{ type: \"text\", text: `Ledger: ${queryType}\\nEndpoint: ${endpoints[queryType]}` }] };\n}\n```\n\nAdded 5 tools: financial_dashboard, financial_ledger, financial_invoices, financial_report, financial_portfolio. Each maps to the corresponding SpiderNetOS API endpoint."}
        ],
        "metadata": {"quality_score": 4, "source": "cursor", "tags": ["financial-os", "mcp", "tools", "typescript", "pattern"]}
    },
    {
        "messages": [
            {"role": "user", "content": "Create the FinanceAgent and ComplianceAgent Python agents."},
            {"role": "assistant", "content": "Created 2 agents in `intelligence/agents/`:\n\n**FinanceAgent** (finance_agent.py) — extends AgentBase:\n```python\nclass FinanceAgent(AgentBase):\n    def __init__(self, meta_planner, cost_governor, memory_graph, db_pool):\n        super().__init__(agent_id='finance', name='Finance',\n            capabilities=['ledger-query', 'report-generation', 'cash-flow-analysis', 'budget-optimization', 'invoice-chasing', 'forecasting', 'financial-qna'],\n            meta_planner=meta_planner, cost_governor=cost_governor, memory_graph=memory_graph)\n        self.db = db_pool\n\n    async def execute(self, context: AgentContext) -> AgentResult:\n        handlers = {\n            'query_ledger': self._query_ledger,\n            'generate_report': self._generate_report,\n            'analyze_cashflow': self._analyze_cashflow,\n            'analyze_budget': self._analyze_budget,\n            'invoice_status': self._invoice_status,\n            'forecast': self._forecast,\n            'financial_qna': self._financial_qna,\n        }\n        return await handlers.get(context.ast.get('type', ''), self._financial_qna)(context)\n\n    async def _query_db(self, query: str, params: list) -> list:\n        try:\n            async with self.db.acquire() as conn:\n                return [dict(r) for r in await conn.fetch(query, *params)]\n        except Exception:\n            return []\n```\n\n**ComplianceAgent** (compliance_agent.py) — extends AgentBase with capabilities: transaction-monitoring, fraud-detection, kyc-screening, audit-trail, alert-management, risk-scoring. Risk scoring: large amount +20, new counterparty +30, high frequency +25, unusual hours +15. Threshold >= 50 = flagged.\n\nBoth use the standard pattern: extend AgentBase, define capabilities, implement execute() with AST routing, use _query_db() helper."}
        ],
        "metadata": {"quality_score": 4, "source": "cursor", "tags": ["financial-os", "agents", "python", "intelligence", "pattern"]}
    },
    {
        "messages": [
            {"role": "user", "content": "Create the Cockpit UI views and router updates for the Financial OS."},
            {"role": "assistant", "content": "Created 5 Vue components in `cockpit/src/views/financial/`:\n\n**Pattern for all financial views:**\n```vue\n<template>\n  <div class=\"financial-domain p-6 space-y-6\" :style=\"{ background: 'var(--bg)' }\">\n    <div>\n      <h1 class=\"text-2xl font-bold\" :style=\"{ color: 'var(--text-primary)' }\">Domain Name</h1>\n      <p class=\"text-sm mt-1\" :style=\"{ color: 'var(--text-secondary)' }\">Description</p>\n    </div>\n    <!-- KPI cards, tables, modals using dct-card, dct-btn-primary, dct-pill-* classes -->\n  </div>\n</template>\n\n<script setup>\nimport { ref, onMounted } from 'vue'\nimport { api } from '../../services/api.js'\n\nconst data = ref([])\nonMounted(async () => {\n    const res = await api.get('/api/financial/endpoint')\n    data.value = res.data.data?.data || []\n})\n</script>\n```\n\n**Components created:**\n1. FinancialDashboard.vue — KPI cards, recent activity, alerts\n2. FinancialLedger.vue — account cards, ledger table, journal entry modal\n3. Invoices.vue — summary, filterable list, create modal with line items\n4. Payments.vue — summary cards, payment history table\n5. Portfolios.vue — portfolio cards with P&L, create modal\n\n**Router updates** in `cockpit/src/router/index.js`:\n```javascript\n// Lazy imports\nconst FinancialDashboard = () => import('../views/financial/FinancialDashboard.vue')\nconst FinancialLedger = () => import('../views/financial/FinancialLedger.vue')\n// ... etc\n\n// Routes\n{ path: '/financial', name: 'FinancialDashboard', component: FinancialDashboard, meta: { requiresAuth: true } },\n{ path: '/financial/ledger', name: 'FinancialLedger', component: FinancialLedger, meta: { requiresAuth: true } },\n{ path: '/financial/invoices', name: 'Invoices', component: Invoices, meta: { requiresAuth: true } },\n{ path: '/financial/payments', name: 'Payments', component: Payments, meta: { requiresAuth: true } },\n{ path: '/financial/portfolios', name: 'Portfolios', component: Portfolios, meta: { requiresAuth: true } },\n```\n\nThis pattern is replicable for any new vertical: create views/{domain}/ directory, Vue components, lazy imports, routes."}
        ],
        "metadata": {"quality_score": 4, "source": "cursor", "tags": ["financial-os", "vue", "cockpit", "router", "pattern"]}
    },
    {
        "messages": [
            {"role": "user", "content": "Give me the complete step-by-step checklist to build ANY new vertical application on SpiderNetOS."},
            {"role": "assistant", "content": "The SpiderNetOS Vertical Application Blueprint — replicable for ANY domain:\n\n**Phase 1: Database (1-2 hours)**\n□ Create migrations in `backend/database/migrations/` — UUID PKs, tenant_id, proper types, indexes\n□ Run `php artisan migrate` and verify tables exist\n\n**Phase 2: Models (1-2 hours)**\n□ Create Eloquent models in `backend/app/Models/` — HasUuids, fillable, casts, relationships, scopes\n□ Every model gets `scopeForTenant()` and domain-specific scopes\n\n**Phase 3: Services (2-4 hours)**\n□ Create service classes in `backend/app/Services/{Domain}/`\n□ Inject EventStore for audit trail on all write operations\n□ Use DB::transaction for atomicity\n□ Business logic lives here, not in controllers\n\n**Phase 4: Controllers (1-2 hours)**\n□ Create controllers in `backend/app/Http/Controllers/{Domain}/`\n□ Constructor injection of services\n□ Laravel validation before calling services\n□ Return `['data' => ...]` format, paginate lists\n\n**Phase 5: Routes (30 min)**\n□ Add to `backend/routes/api.php` under `Route::prefix('domain')`\n□ Group with auth:sanctum + tenant + onboarding.required middleware\n□ RESTful naming\n\n**Phase 6: Integrations (1-2 hours per provider)**\n□ Create adapter in `backend/app/Services/Integrations/{Provider}Adapter.php`\n□ Constructor takes tenantId + credentials\n□ Methods return arrays, use Http facade\n\n**Phase 7: Feature Pack (30 min)**\n□ Create `packages/feature-packs/{domain}/pack.yaml`\n□ Define dynamic_agents, ste_chains, policies\n□ List all migrations\n\n**Phase 8: MCP Tools (1 hour)**\n□ Add Tool definitions to `services/mcp-server/src/server.ts`\n□ Register in ListToolsRequestSchema\n□ Implement in CallToolRequestSchema switch\n\n**Phase 9: AI Agents (2-4 hours)**\n□ Create `intelligence/agents/{domain}_agent.py`\n□ Extend AgentBase with capabilities list\n□ Implement execute() with AST type routing\n□ Use _query_db() helper\n\n**Phase 10: Cockpit UI (2-4 hours)**\n□ Create `cockpit/src/views/{domain}/` directory\n□ Vue 3 components with setup syntax\n□ Use existing CSS classes (dct-card, dct-btn-primary, etc.)\n□ Lazy-load in router, add routes with requiresAuth: true\n\n**Total: ~15-25 hours for a complete vertical application.**\n\n**The Financial OS was built using this exact pattern in a single session.**"}
        ],
        "metadata": {"quality_score": 4, "source": "cursor", "tags": ["spidernetos-pattern", "blueprint", "replicable", "methodology", "checklist"]}
    },
    {
        "messages": [
            {"role": "user", "content": "How does the event-sourced financial ledger integrate with SpiderNetOS's existing EventStore?"},
            {"role": "assistant", "content": "The Financial OS leverages SpiderNetOS's existing EventStore for audit-grade immutability:\n\n**Every financial operation appends to event_log:**\n- LedgerService::createJournalEntry() → `ledger.entry_posted`\n- InvoiceService::createInvoice() → `invoice.created`\n- PaymentService::recordPayment() → `payment.received`\n- PortfolioService::executeTrade() → `trade.executed`\n\n**EventStore guarantees (from the core system):**\n1. Append-only — events are never deleted or modified\n2. Hash chaining — each event's hash includes previous_hash (tamper-evident)\n3. Global sequence numbering — total ordering across all events\n4. Optimistic concurrency — expectedVersion check prevents lost writes\n5. Tenant isolation — every event scoped by tenant_id\n6. Key signing — HMAC-SHA256 with per-tenant signing key\n\n**The double-entry ledger_entries table is a projection of events:**\n- Materialized view for fast queries\n- EventStore::append() records the immutable source\n- `rebuildProjection()` can reconstruct from event_log if needed\n- ComplianceAgent's `_audit_trail()` verifies hash chain integrity\n\n**This means the Financial OS inherits the same audit-grade immutability as the core SpiderNetOS system.** Any financial action can be replayed, verified, and audited. This is a significant advantage over standalone financial platforms that must build audit trails from scratch."}
        ],
        "metadata": {"quality_score": 4, "source": "cursor", "tags": ["financial-os", "event-sourcing", "audit", "immutability", "integration"]}
    },
    {
        "messages": [
            {"role": "user", "content": "How should I test the Financial OS after implementing it?"},
            {"role": "assistant", "content": "Testing the Financial OS:\n\n**1. Migrations:**\n```bash\ncd backend && php artisan migrate --pretend && php artisan migrate && php artisan migrate:rollback\n```\n\n**2. API testing:**\n```bash\nPOST /api/financial/ledger/accounts -d '{\"name\":\"Cash\",\"type\":\"asset\"}'\nPOST /api/financial/ledger/journal-entry -d '{\"source_account_id\":\"...\",\"destination_account_id\":\"...\",\"amount\":100}'\nGET /api/financial/ledger/trial-balance\nPOST /api/financial/invoices -d '{\"customer_name\":\"Test\",\"due_date\":\"2026-06-01\",\"line_items\":[{\"description\":\"Service\",\"unit_price\":100}]}'\nPOST /api/financial/payments -d '{\"amount\":100,\"method\":\"card\",\"idempotency_key\":\"test-1\"}'\nGET /api/financial/dashboard\n```\n\n**3. Verify:**\n- Every operation creates an event_log entry\n- Trial balance: total debits = total credits\n- Idempotency: same idempotency_key returns same result\n- Fraud detection: amount > 10000 creates FinancialAlert\n- Stripe webhook: use Stripe CLI for test events\n- Cockpit UI: /financial, /financial/ledger, /financial/invoices, /financial/payments, /financial/portfolios all render\n\n**4. Run quality gate on training data:**\n```bash\npython scripts/eval_training_data_quality.py --sft training_data/sft.jsonl --preference training_data/preference.jsonl\n```\n\n**5. Verify feature pack:**\n```bash\npython scripts/validate_feature_pack.py packages/feature-packs/financial-services/pack.yaml\n```"}
        ],
        "metadata": {"quality_score": 4, "source": "cursor", "tags": ["financial-os", "testing", "verification", "quality"]}
    },
    {
        "messages": [
            {"role": "user", "content": "What are the architectural advantages of building on SpiderNetOS vs a standalone platform?"},
            {"role": "assistant", "content": "SpiderNetOS provides these advantages out of the box:\n\n1. **Event-Sourced Audit Trail** — event_log with hash chaining provides tamper-evident records. Standalone platforms build this from scratch.\n\n2. **Multi-Tenant Isolation** — every table scoped by tenant_id with middleware enforcement. No data leakage.\n\n3. **AI-Native** — built-in agents with capabilities like natural language Q&A, fraud detection, forecasting. AI is core, not bolted-on.\n\n4. **Agent Delegation Graph** — agents can delegate to each other (FinanceAgent → ComplianceAgent → PortfolioAgent).\n\n5. **State Transition Engine** — automatic state machine projections for workflows.\n\n6. **Human-in-the-Loop** — approvals table integrates seamlessly for required sign-offs.\n\n7. **Cost Governance** — prevents runaway AI spending on computations.\n\n8. **Real-Time** — Soketi WebSockets for live updates.\n\n9. **MCP Protocol** — AI tools accessible via Model Context Protocol.\n\n10. **Feature Pack System** — versioned, installable vertical applications with auto-provisioning.\n\n11. **Memory Graph** — pgvector + Neo4j for cross-agent knowledge sharing.\n\n12. **Inference Plane** — policy-based model routing across OpenAI, Anthropic, Ollama with cost-aware fallback.\n\n13. **Observability** — trace replay, divergence detection, anomaly monitoring.\n\n14. **Voice AI** — built-in telephony with Twilio integration.\n\n15. **Training Data Pipeline** — SFT/preference data with quality gates for continuous improvement.\n\n**Building the Financial OS on SpiderNetOS took one session. Building it standalone would take weeks.**"}
        ],
        "metadata": {"quality_score": 4, "source": "cursor", "tags": ["spidernetos-pattern", "advantages", "architecture", "comparison"]}
    },
]

# ─── Preference entries ──────────────────────────────────────────────────
pref_entries = [
    {
        "prompt": "Build a complete Financial OS for SpiderNetOS with double-entry bookkeeping, invoicing, payments, and portfolios.",
        "chosen": "I'll build the complete Financial OS following the SpiderNetOS 10-step pattern:\n1. 15 migrations in backend/database/migrations/ — UUID PKs, tenant_id, DECIMAL(19,4) for money\n2. 17 Eloquent models in backend/app/Models/ — HasUuids, fillable, casts, relationships, scopes\n3. 6 services in backend/app/Services/Financial/ — LedgerService (double-entry), InvoiceService, PaymentService, ReportingService, FinancialGovernor, PortfolioService\n4. 5 controllers in backend/app/Http/Controllers/Financial/ — LedgerController, InvoiceController, PaymentController, FinancialController, PortfolioController\n5. 30+ routes in backend/routes/api.php under /api/financial prefix\n6. StripeAdapter in backend/app/Services/Integrations/\n7. Feature pack in packages/feature-packs/financial-services/pack.yaml\n8. 5 financial tools in services/mcp-server/src/server.ts\n9. 2 Python agents in intelligence/agents/ — FinanceAgent, ComplianceAgent\n10. 5 Vue views in cockpit/src/views/financial/ + router updates\nAll tables use DECIMAL(19,4) for financial precision. Every write goes through EventStore for audit.",
        "rejected": "Just create a few database tables and a basic API. You don't need services, agents, MCP tools, or a feature pack. Keep it simple.",
        "metadata": {"quality_score": 4, "rejected_type": "missing_architecture", "tags": ["financial-os", "architecture"]}
    },
    {
        "prompt": "Create database migrations for the Financial OS.",
        "chosen": "Created 15 migrations with DECIMAL(19,4) for all money fields, UUID primary keys, tenant_id on every table, composite unique constraints, and proper indexes. Used Schema::dropIfExists() in all down() methods. Tables: financial_accounts, chart_of_accounts, ledger_entries, transactions, invoices, invoice_line_items, payments, subscriptions, wallets, wallet_transactions, budgets, customers, tax_rates, portfolios, portfolio_positions, trades, financial_reports, financial_alerts.",
        "rejected": "Create the tables with FLOAT for money fields — it's simpler and works fine for most amounts.",
        "metadata": {"quality_score": 4, "rejected_type": "missing_financial_precision", "tags": ["financial-os", "database", "precision"]}
    },
    {
        "prompt": "Implement the LedgerService for double-entry bookkeeping.",
        "chosen": "LedgerService wraps all operations in DB::transaction, creates paired debit/credit entries with identical amounts, appends to EventStore for audit, and atomically updates account balances. getTrialBalance() verifies debits equal credits. getGeneralLedger() returns entries per account. getCashFlow() categorizes into operating/investing/financing.",
        "rejected": "Just create a single ledger entry per transaction and update the balance. Double-entry is overkill.",
        "metadata": {"quality_score": 4, "rejected_type": "missing_double_entry", "tags": ["financial-os", "ledger", "accounting"]}
    },
    {
        "prompt": "Implement the PaymentService with idempotency.",
        "chosen": "PaymentService checks idempotency_key before creating payments — if key exists, returns existing payment. Wraps in DB::transaction. Appends to EventStore. Supports incoming (recordPayment) and outgoing (initiatePayment → completePayment/failPayment) flows. getPaymentSummary() returns total_received, total_sent, pending, net.",
        "rejected": "Just create the payment record without checking for duplicates. The client should handle retries.",
        "metadata": {"quality_score": 4, "rejected_type": "missing_idempotency", "tags": ["financial-os", "payments", "reliability"]}
    },
    {
        "prompt": "Implement fraud detection for the Financial OS.",
        "chosen": "FinancialGovernor uses additive risk scoring: large amount >$10K (+20), new counterparty with large amount (+30), high frequency >5 txns/30min (+25), unusual hours 2am-5am (+15). Score >= 50 creates FinancialAlert and flags transaction. Creates alerts for budget exceeded/warning. All thresholds configurable per tenant.",
        "rejected": "Just flag any transaction over $10,000. That catches all fraud.",
        "metadata": {"quality_score": 4, "rejected_type": "suboptimal_algorithm", "tags": ["financial-os", "fraud-detection", "risk"]}
    },
    {
        "prompt": "Create the PortfolioService for the Financial OS.",
        "chosen": "PortfolioService manages positions with averaged cost basis on repeated buys. executeTrade() wraps in DB::transaction, creates Trade record, updates/deletes position, appends to EventStore. updatePositionPrices() recalculates market_value and unrealized_pnl for each position. getPortfolioPerformance() sums value, cost, P&L across positions.",
        "rejected": "Just store each trade as a separate record and calculate totals on the fly. No need for position tracking.",
        "metadata": {"quality_score": 4, "rejected_type": "missing_aggregation", "tags": ["financial-os", "portfolio", "trading"]}
    },
    {
        "prompt": "Create the financial API controllers and routes.",
        "chosen": "5 controllers in backend/app/Http/Controllers/Financial/ with constructor injection, Laravel validation, tenant scope via $request->attributes->get('tenant'), consistent ['data' => ...] response format, pagination for lists. 30+ routes under Route::prefix('financial') with auth:sanctum + tenant + onboarding.required middleware.",
        "rejected": "Put all the logic in the controllers directly. No need for service classes or validation.",
        "metadata": {"quality_score": 4, "rejected_type": "missing_architecture", "tags": ["financial-os", "controllers", "api"]}
    },
    {
        "prompt": "Create the Stripe adapter for the Financial OS.",
        "chosen": "StripeAdapter with constructor taking tenantId + credentials, throws if api_key missing. Methods: createPaymentIntent (amount*100 for cents), createCustomer, createSubscription, createInvoice, verifyPayment, refundPayment, handleWebhook (Stripe signature verification, maps event types to internal format). Uses Laravel Http facade.",
        "rejected": "Hard-code the Stripe API calls in the controller. No need for a separate adapter class.",
        "metadata": {"quality_score": 4, "rejected_type": "missing_extensibility", "tags": ["financial-os", "stripe", "adapter"]}
    },
    {
        "prompt": "Create the financial feature pack YAML.",
        "chosen": "pack.yaml defines 3 dynamic_agents (finance, compliance, portfolio) with capabilities, 2 ste_chains (payment_lifecycle, invoice_lifecycle), 2 policies (transaction approval >$10K, budget enforcement at 100%), lists all 15 migrations, declares Stripe integration with adapter class path.",
        "rejected": "Just create the migrations and skip the feature pack. It's not needed.",
        "metadata": {"quality_score": 4, "rejected_type": "missing_integration", "tags": ["financial-os", "feature-pack", "packaging"]}
    },
    {
        "prompt": "Add financial tools to the MCP server.",
        "chosen": "Added 5 Tool objects to server.ts: financial_dashboard, financial_ledger, financial_invoices, financial_report, financial_portfolio. Each has name, description, inputSchema with typed properties. Registered in ListToolsRequestSchema. Implemented in CallToolRequestSchema switch with case blocks mapping to API endpoints.",
        "rejected": "Skip the MCP tools. AI agents can just call the REST API directly.",
        "metadata": {"quality_score": 4, "rejected_type": "missing_quality", "tags": ["financial-os", "mcp", "tools"]}
    },
    {
        "prompt": "Create the FinanceAgent and ComplianceAgent Python agents.",
        "chosen": "FinanceAgent extends AgentBase with capabilities for ledger-query, report-generation, cash-flow-analysis, budget-optimization, invoice-chasing, forecasting, financial-qna. Execute() routes AST types to handlers. ComplianceAgent extends AgentBase with transaction-monitoring, fraud-detection, kyc-screening, audit-trail, alert-management, risk-scoring. Both use meta_planner, cost_governor, memory_graph, db_pool dependencies.",
        "rejected": "Just add the capabilities to the existing Atlas agent. No need for separate agents.",
        "metadata": {"quality_score": 4, "rejected_type": "suboptimal_design", "tags": ["financial-os", "agents", "architecture"]}
    },
    {
        "prompt": "Create the Cockpit UI for the Financial OS.",
        "chosen": "5 Vue components in cockpit/src/views/financial/: FinancialDashboard (KPIs, recent activity, alerts), FinancialLedger (account cards, entries table, modals), Invoices (summary, filterable list, create modal), Payments (summary, history), Portfolios (cards with P&L). Lazy-loaded in router with requiresAuth: true. Uses existing dct-card, dct-btn-primary, dct-pill-* CSS classes.",
        "rejected": "Create a single page with all financial data. No need for separate views or routing.",
        "metadata": {"quality_score": 4, "rejected_type": "suboptimal_design", "tags": ["financial-os", "vue", "cockpit"]}
    },
    {
        "prompt": "What is the general SpiderNetOS pattern for building any new vertical application?",
        "chosen": "The 10-step SpiderNetOS pattern: 1) Migrations (UUID PKs, tenant_id, proper types), 2) Models (HasUuids, fillable, casts, relationships, scopes), 3) Services (EventStore integration, DB::transaction), 4) Controllers (validation, thin, JSON responses), 5) Routes (prefix group with auth middleware), 6) Integration Adapters (tenantId + credentials, Http facade), 7) Feature Pack (YAML with agents, state machines, policies), 8) MCP Tools (Tool objects in server.ts), 9) AI Agents (extend AgentBase, AST routing), 10) Cockpit UI (Vue components, lazy router). This pattern is replicable for any domain — HR, logistics, healthcare, e-commerce, etc.",
        "rejected": "Just create the database tables and API endpoints. That's all you need for a new feature.",
        "metadata": {"quality_score": 4, "rejected_type": "missing_architecture", "tags": ["spidernetos-pattern", "methodology", "replicable"]}
    },
    {
        "prompt": "How does the event-sourced financial ledger integrate with SpiderNetOS EventStore?",
        "chosen": "Every financial operation appends to event_log: ledger.entry_posted, invoice.created, payment.received, trade.executed. EventStore guarantees append-only records, hash chaining (tamper-evident), global sequence numbering, optimistic concurrency, tenant isolation, and HMAC-SHA256 signing. The ledger_entries table is a projection of events — rebuildable via rebuildProjection(). ComplianceAgent verifies hash chain integrity.",
        "rejected": "Just store financial records in the database tables. Event sourcing adds unnecessary complexity.",
        "metadata": {"quality_score": 4, "rejected_type": "missing_immutability", "tags": ["financial-os", "event-sourcing", "audit"]}
    },
    {
        "prompt": "How should I test the Financial OS after implementation?",
        "chosen": "Test in order: 1) Migrations (migrate --pretend, migrate, migrate:rollback), 2) API endpoints (curl/Postman for each controller), 3) Event log (verify every operation creates event), 4) Trial balance (debits = credits), 5) Idempotency (same key returns same result), 6) Fraud detection (large amount creates alert), 7) Stripe webhooks (Stripe CLI test events), 8) Cockpit UI (all routes render), 9) Feature pack validation (validate_feature_pack.py), 10) Training data quality gate (eval_training_data_quality.py).",
        "rejected": "Just test the API endpoints manually. That's sufficient.",
        "metadata": {"quality_score": 4, "rejected_type": "missing_validation", "tags": ["financial-os", "testing", "quality"]}
    },
    {
        "prompt": "What are the advantages of building the Financial OS on SpiderNetOS vs standalone?",
        "chosen": "SpiderNetOS provides out of the box: event-sourced audit trail, multi-tenant isolation, AI-native agents, agent delegation graph, state transition engine, human-in-the-loop approvals, cost governance, real-time WebSockets, MCP protocol, feature pack system, memory graph, inference plane, observability, voice AI, and training data pipeline. Building the Financial OS on SpiderNetOS took one session. Building standalone would take weeks.",
        "rejected": "There are no real advantages. Building standalone gives you more control and flexibility.",
        "metadata": {"quality_score": 4, "rejected_type": "suboptimal_design", "tags": ["financial-os", "advantages", "comparison"]}
    },
    {
        "prompt": "How do you add a new integration adapter (e.g., Plaid) following the SpiderNetOS pattern?",
        "chosen": "1) Create PlaidAdapter.php in backend/app/Services/Integrations/ with constructor taking tenantId + credentials, 2) Implement domain methods using Laravel Http facade, 3) Store OAuth tokens in tenant_integrations table via TenantKeyManager encryption, 4) Add to IntegrationsController for OAuth flow, 5) Reference in feature pack YAML under spec.integrations, 6) Follow existing adapter patterns (StripeAdapter, CrmAdapter).",
        "rejected": "Just make HTTP calls directly in the controller where you need them. No adapter needed.",
        "metadata": {"quality_score": 4, "rejected_type": "missing_extensibility", "tags": ["financial-os", "integration", "adapter-pattern"]}
    },
    {
        "prompt": "How do you ensure financial precision in the SpiderNetOS Financial OS?",
        "chosen": "Use DECIMAL(19,4) for all money fields in migrations (prevents floating-point rounding errors). Use 'decimal:4' cast in Eloquent models. Calculate totals server-side in services (never trust client-side calculations). Use DB::transaction for atomic operations. Verify trial balance (debits = credits) after every journal entry. Use idempotency keys to prevent double-processing.",
        "rejected": "Use regular FLOAT columns. The precision loss is negligible for most financial amounts.",
        "metadata": {"quality_score": 4, "rejected_type": "missing_financial_precision", "tags": ["financial-os", "precision", "best-practices"]}
    },
]

# Write SFT entries
sft_path = os.path.join(BASE, "sft.jsonl")
with open(sft_path, "a", encoding="utf-8") as f:
    for entry in sft_entries:
        f.write(json.dumps(entry, ensure_ascii=False) + "\n")

# Write preference entries
pref_path = os.path.join(BASE, "preference.jsonl")
with open(pref_path, "a", encoding="utf-8") as f:
    for entry in pref_entries:
        f.write(json.dumps(entry, ensure_ascii=False) + "\n")

# Verify
sft_count = sum(1 for _ in open(sft_path, encoding="utf-8"))
pref_count = sum(1 for _ in open(pref_path, encoding="utf-8"))

print(f"SFT entries: {sft_count}")
print(f"Preference entries: {pref_count}")
print(f"SFT added: {len(sft_entries)}")
print(f"Preference added: {len(pref_entries)}")
print(f"Total SFT: {sft_count} (need >= 20)")
print(f"Total Preference: {pref_count} (need >= 20)")
